AWSTemplateFormatVersion: "2010-09-09"
Description: Basic EC2 Instance

Parameters:
  MyKeyName:
    Description: select the key name
    Type: "AWS::EC2::KeyPair::KeyName"
  MyAvailabilityZone:
    Description: select the availability zone
    Type: String
    Default: eu-west-2a
    AllowedValues:
      - eu-west-2a
      - eu-west-2b
      - eu-west-2c
  MyInstanceType:
    Description: select the ec2 instance type from parameter store
    Type: "AWS::SSM::Parameter::Value<String>"

Resources:
  DevEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-0dd555eb7eb3b7c82
      InstanceType: !Ref MyInstanceType
      KeyName: !Ref MyKeyName
      SecurityGroups:
        - default
        - !Ref SSHSecurityGroup
      AvailabilityZone: !Ref MyAvailabilityZone
      Tags:
        - Key: Name
          Value: dev-ec2-instance

  SSHSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: my new SSH security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0

  ElasticIP:
    Type: "AWS::EC2::EIP"
    Properties:
      InstanceId: !Ref DevEC2Instance